### PR TITLE
added in ability to disable it

### PR DESCRIPTION
**Pull request by brechmos**

### CODE REVIEW

**Comment by tomatohater** [comment]
I like the idea behind this, but there are a few issues...

1) The new setting needs to implement the getattr() pattern like all the other settings so that it can be overridden in the application's Django settings.

2) I'd be more explicit about what "enable" means. It's really just the template tag filter that is on or off. The view renderer should always be on. Perhaps naming the setting more explicitly would suffice.

3) Need unit tests to ensure that all code paths are covered.

I'm open to fixing these myself. Let me know if you'd like me to do that, but I'll give you the option first.

**Comment by tomatohater** [comment]
Closing this PR in favor of #14 (merge into a feature branch for further mods).

**Comment by brechmos** [comment]
Honestly, I hit pull request by mistake.  I fixed the getattr already.  I
am fine if you change the setting name from ENABLE to something else.  I
think it makes sense but it is great with me you have other ideas.

I would like to leave the unit tests to you, sorry.

I'll send another pull request with the getattr

On Sun, Feb 1, 2015 at 2:12 PM, Drew Engelson <notifications@github.com>
wrote:

> I like the idea behind this, but there are a few issues...
>
> 1) The new setting needs to implement the getattr() pattern like all the
> other settings so that it can be overridden in the application's Django
> settings.
>
> 2) I'd be more explicit about what "enable" means. It's really just the
> template tag filter that is on or off. The view renderer should always be
> on. Perhaps naming the setting more explicitly would suffice.
>
> 3) Need unit tests to ensure that all code paths are covered.
>
> I'm open to fixing these myself. Let me know if you'd like me to do that,
> but I'll give you the option first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomatohater/django-unfriendly/pull/13#issuecomment-72378939>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by tomatohater** [comment]
Thanks, Chris. I can take it from here. I'll close this out and work with #15.

**Comment by tomatohater** [comment]
Sorry. I meant Craig.

**Comment by tomatohater** [comment]
Craig,

Your code has been pushed into the master branch. I made a few tweaks and
added tests, so now we have passing tests with 100% coverage.

I've also packaged up the change as release v0.4.1 and sent it up to PyPi:
https://pypi.python.org/pypi/django-unfriendly/0.4.1

Thanks again for the contribution!

Sincerely,
Drew

**Comment by brechmos** [comment]
Thanks!  That's great. I appreciate your desire to add it.  Very helpful
for me.  :-)



On Sun, Feb 1, 2015 at 8:25 PM, Drew Engelson <notifications@github.com>
wrote:

> Craig,
>
> Your code has been pushed into the master branch. I made a few tweaks and
> added tests, so now we have passing tests with 100% coverage.
>
> I've also packaged up the change as release v0.4.1 and sent it up to PyPi:
> https://pypi.python.org/pypi/django-unfriendly/0.4.1
>
> Thanks again for the contribution!
>
> Sincerely,
> Drew
>
>
>
>
>
>
> On Sun, Feb 1, 2015 at 4:17 PM, brechmos <notifications@github.com>
> wrote:
>
> > Honestly, I hit pull request by mistake. I fixed the getattr already. I
> > am fine if you change the setting name from ENABLE to something else. I
> > think it makes sense but it is great with me you have other ideas.
> >
> > I would like to leave the unit tests to you, sorry.
> >
> > I'll send another pull request with the getattr
> >
> > On Sun, Feb 1, 2015 at 2:12 PM, Drew Engelson <notifications@github.com>
>
> > wrote:
> >
> > > I like the idea behind this, but there are a few issues...
> > >
> > > 1) The new setting needs to implement the getattr() pattern like all
> the
> > > other settings so that it can be overridden in the application's
> Django
> > > settings.
> > >
> > > 2) I'd be more explicit about what "enable" means. It's really just
> the
> > > template tag filter that is on or off. The view renderer should always
> > be
> > > on. Perhaps naming the setting more explicitly would suffice.
> > >
> > > 3) Need unit tests to ensure that all code paths are covered.
> > >
> > > I'm open to fixing these myself. Let me know if you'd like me to do
> > that,
> > > but I'll give you the option first.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/tomatohater/django-unfriendly/pull/13#issuecomment-72378939>
>
> >
> > > .
> > >
> >
> >
> >
> > --
> >
> >
> > Craig Jones
> > craigj@jhu.edu
> > 443-712-8152
> > mri.jhu.edu/~craig
> > Google Talk: brechmos
> > Skype: brechmos
> > FM Kirby Center, Kennedy Krieger Institute
> > Dept of Radiology, Johns Hopkins Medical Insitutes
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/tomatohater/django-unfriendly/pull/13#issuecomment-72384693>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomatohater/django-unfriendly/pull/13#issuecomment-72395866>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Pull request closed without merging**
