### PR TITLE
Attempting to fix URLs for Django 1.10

### PR DESCRIPTION
**Pull request by kylebamos**

### CODE REVIEW

**Comment by kylebamos** [comment]
@tomatohater Thanks. I was just going through some of our builds and noticed RemovedInDjango110Warnings . Please let me know if any of this is off-base.

**Comment by tomatohater** [comment]
Hey @kylebamos Thanks for all your work here.

Your code additions definitely do the job, however, in the spirit of keeping the codebase as simple as possible, I've decided to drop compatibility for Django versions prior to 1.8 which are no longer supported by the Django Software Foundation.

I'm about to push a fresh version that cleans this all up.

**Comment by kylebamos** [comment]
Sounds good. Thanks @tomatohater

**Comment by tomatohater** [comment]
Hey @kylebamos 

I pushed out v0.5 yesterday which includes your changes... then I removed all the cruft for pre-Django 1.8.

- https://pypi.python.org/pypi/django-unfriendly/0.5.0
- https://github.com/tomatohater/django-unfriendly/graphs/contributors
- https://github.com/tomatohater/django-unfriendly/releases

I feel better having deprecated those versions because next up is Python3 compatibility. ;)

**Pull request merged**
